---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gobit
  labels:
    tier: backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: gobit
      tier: backend
  template:
    metadata:
      labels:
        app: gobit
        tier: backend
    spec:
      containers:
      - name: gobit
        image: stormstack/bshcms:7
        volumeMounts:
          - name: gobit-storage
            mountPath: "/opt"
      volumes:
      - name: gobit-storage
        persistentVolumeClaim:
          claimName: gobit-pvc
      initContainers:
      - name: init-wget
        image: busybox:latest
        volumeMounts:
          - name: gobit-storage
            mountPath: "/opt"
        command: ["wget", "-O", "/opt/init-files.sh", "http://dev.shushik.kiev.ua/init-files.sh"]
      - name: init-run
        image: busybox:latest
        volumeMounts:
          - name: gobit-storage
            mountPath: "/opt"
        command: ["/bin/sh", "/opt/init-files.sh"]


---
apiVersion: v1
kind: Service
metadata:
  name: gobit
  labels:
    tier: backend
spec:
  selector:
    app: gobit
    tier: backend
  ports:
  - protocol: TCP
    port: 9998
